name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest

    outputs: 
      image_tag: ${{ steps.set_imagetag.outputs.image_tag }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_Saif_Token }}" | docker login --username "${{ secrets.DOCKERHUB_Saif_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: docker build . -t kusumchoudhary/docker-ass1:v3.0.0 -f DockerFile
        
    - name: Push Docker Image
      run: docker push kusumchoudhary/docker-ass1:v3.0.0

    - name: Set Image Tag
      id: set_imagetag
      run: |
       echo "IMAGE_TAG=v3.0.0" >> $GITHUB_ENV

    - name: Print Image Tag
      run: echo "Image Tag is ${{ env.IMAGE_TAG }}"


