name: Build and Push Docker Image

on:
  push:
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_Saif_Token }}" | docker login --username "${{ secrets.DOCKERHUB_Saif_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: docker build . -t kusumchoudhary/docker-ass1:v2.0.0 -f DockerFile

    - name: Push Docker Image
      run: docker push kusumchoudhary/docker-ass1:v2.0.0

    - name: Set Image Tag Output
      id: set-tag
      run: echo "::set-output name=tag::${{ steps.build-and-push.outputs.image_tag }}"
