name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.build.outputs.image_tag }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_Saif_Token }}" | docker login --username "${{ secrets.DOCKERHUB_Saif_USERNAME }}" --password-stdin

    - name: Build Docker Image
      id: build
      run: |
        docker build . -t kusumchoudhary/docker-ass1:v5.0.0 -f DockerFile
        echo "v5.0.0" >> $GITHUB_ENV  # Store the image tag in an environment variable

    - name: Push Docker Image
      run: docker push kusumchoudhary/docker-ass1:v5.0.0

    - name: Set Image Tag Output
      if: always()
      run: echo "image_tag=v5.0.0" >> $GITHUB_ENV
