name: Print Docker Image Tag

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  print-tag:
    name: Print Docker Image Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Read Image Tag from Environment File
        run: |
          echo "Docker image tag: $TAG" >> image_tag.txt

      - name: Print Image Tag
        run: cat image_tag.txt
