name: Print Docker Image Tag

on:
  repository_dispatch:
    types: build-push

jobs:
  print-tag:
    name: Print Docker Image Tag
    runs-on: ubuntu-latest
    steps:
      - name: Extract Image Tag from Payload
        run: echo "Docker image tag: ${{ github.event.client_payload.image_tag }}"
