name: Print Docker Image Tag

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  print-tag:
    name: Print Docker Image Tag
    runs-on: ubuntu-latest
    steps:
      - name: Print Image Tag
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: |
          echo "Docker image tag: ${{ env.IMAGE_TAG }}"
