name: Print Docker Image Tag

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  print-tag:
    name: Print Docker Image Tag
    runs-on: ubuntu-latest
    steps:
      - name: Download image_tag artifact
        uses: actions/download-artifact@v2
        with:
          name: image_tag
          path: .  # Download the artifact to the current directory

      - name: Read Image Tag from File
        run: cat image_tag.txt

      # Add any other steps as needed
